[![Made by Mr.Sahraoui](https://img.shields.io/badge/Made%20by-Mr.Sahraoui-orange)](https://digitalpro.dev)
![NLP](https://img.shields.io/badge/NLP-TP%20%202-orange)

<table style="width: 100%;">
<tr>
<td style="width: 50%; text-align: right; vertical-align: middle;">
<img src="https://github.com/gitpizzanow/dummy-files/blob/main/tp1nlp.jpg?raw=true" width="150">
</td>
<td style="width: 50%; text-align: left; vertical-align: middle;">

##  (NLP)   | Text Manipulation &Fake News Classification
> [SERIE](https://tp1-nlp-ing4.netlify.app/)


* *Text cleaning*
* *Text normalization*
* *Text tokenization*


> [DATA](https://www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets)

</td>
</tr>
</table>

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
import string

punctuations = list(string.punctuation) # Get all punctuation : !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [ ]:
import pandas as pd

fake_df = pd.read_csv('/content/Fake.csv')
true_df = pd.read_csv('/content/True.csv')

In [ ]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
fake_df['label'] = 0
true_df['label'] = 1

In [ ]:
true_df_cols = true_df.columns
fake_df_cols = fake_df.columns

print (true_df_cols)
print (fake_df_cols)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [ ]:
data = pd.concat([fake_df, true_df], ignore_index=True)
data = data.sample(frac=1, random_state=42).reset_index(drop=True) #shuffle the dataset

data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [ ]:
X = data['text'].tolist()[:50]
y = data['label'].tolist()[:50]

![ ](https://img.shields.io/badge/Text_normalization-red)

In [ ]:
!pip install num2words > /dev/null

![ ](https://img.shields.io/badge/Number_to_words_conversion%20%20-blue)

In [ ]:
#comlete the code

![ ](https://img.shields.io/badge/drop_stop_words%20%20-blue)

In [ ]:
#comlete the code

![ ](https://img.shields.io/badge/drop_punctuations%20%20-blue)

In [ ]:
#comlete the code

![ ](https://img.shields.io/badge/Process%20%20-orange)

In [ ]:
#comlete the code

![ ](https://img.shields.io/badge/Vocabs%20%20-blue)

In [ ]:
#comlete the code

## BOW
>1-gram BOW

[![Naive Bayes](https://img.shields.io/badge/Naive_Bayes-classification-pink)](https://digitalpro.dev)

> Convert X docs to NumPy array

In [ ]:
import numpy as np

X_vectors = np.array(Vectors) #define your Vectors
y_array = np.array(y)

> Split into train/test

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectors, y_array, test_size=0.2, random_state=42, stratify=y_array
)

> Train Naive Bayes classifier

In [ ]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, classification_report

nb = BernoulliNB()
nb.fit(X_train, y_train)    # Train

y_pred = nb.predict(X_test) # Predict

> Evaluate

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))